services:
  quiz:
    image: ghcr.io/marvinjwendt/quiz-game/quiz-backend:latest
    container_name: quiz-backend
    restart: always
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.quiz-api.rule=Host(`quiz-api.mjw.dev`)
      - traefik.http.services.quiz-api.loadbalancer.server.port=8080
      - traefik.http.routers.quiz-api.tls=true

networks:
  proxy:
    external: true 